- support downloading a BOOTFILE from a TFTP server

diff --git a/i386-pc/fs_skeleton/etc/init.d/rcLocalS b/i386-pc/fs_skeleton/etc/init.d/rcLocalS
--- a/i386-pc/fs_skeleton/etc/init.d/rcLocalS
+++ b/i386-pc/fs_skeleton/etc/init.d/rcLocalS
@@ -4,14 +4,24 @@ if [ -n "$BOOTCMD" ] ; then
 	/bin/sh -c "$BOOTCMD"
 	# Continue here and let then also specify a BOOTFILE
 fi
+if [ -z "$BOOTFILE" -a -r /etc/bootfile ] ; then
+	BOOTFILE=`cat /etc/bootfile`
+fi
 if [ -n "$BOOTFILE" ] ; then
+	RGX='\(^tftp:[/][/]\)\([^/]*\)\([/]\)\(\([^/]*[/]\)*\)\(.*\)'
+	TFTP_HOST=`echo -n "$BOOTFILE" | sed -n -e "s%$RGX%\2%p"`
+	TFTP_PATH=`echo -n "$BOOTFILE" | sed -n -e "s%$RGX%\4\6%p"`
+	TFTP_FILN=`echo -n "$BOOTFILE" | sed -n -e "s%$RGX%\6%p"`
+	if [ -n "$TFTP_HOST" -a -n "$TFTP_PATH" -a -n "$TFTP_FILN" ] ; then
+		mkdir -p /boot/tftp/
+		BOOTFILE=/boot/tftp/"$TFTP_FILN"
+		echo "Copying BOOTFILE via TFTP to $BOOTFILE"
+		echo "tftp -r $TFTP_PATH -l $BOOTFILE -g $TFTP_HOST && chmod a+x $BOOTFILE"
+		tftp -r $TFTP_PATH -l $BOOTFILE -g $TFTP_HOST && chmod a+x $BOOTFILE
+	fi
 	echo "Executing BOOTFILE: $BOOTFILE"
 	exec "$BOOTFILE"
+	echo "Executing bootfile FAILED"
+	exit 1
 fi
-if [ -r /etc/bootfile ] ; then
-	BOOTFILE=`cat /etc/bootfile`
-	echo "Executing bootfile: $BOOTFILE"
-	exec "$BOOTFILE"
-fi
-echo "Executing bootfile FAILED"
-exit 1
+echo "No BOOTFILE"
